name: Test SingleM with Setup-Miniconda From Marketplace
on: [push, pull_request]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: test
          environment-file: zenodo_backpack.yml
          python-version: 3.9 # 3.10 fails to setup environment
          # auto-activate-base: false
          # mamba-version: "*" # Appears to be broken as of writing.
          channels: conda-forge,defaults
      - run: |
          conda info
          conda list
      - name: Run pytest
        run: |
            pytest test
